travis:
  secure:
    BINSTAR_TOKEN: 0R+PtgPKUZF0QsxtJqGLOAokg3EmwbK9lKrCyPWGQxnBsrH/niBLmPJcHGCpAhYrCtIaugNWp1p155KiW36X4RSNaVqq+eXsSAPykif47yDwEn4Xrx9lJDktT5khBDyy7f2n+n/ICZkwOxey38ujXiRrj8E6l8qEg13PohN7xUzJeXLIslQOOPpy/g1qJ4QXRMk220Q3r0MFeaKzGbwiwXXXNxPfstuE+f5VmJuWJ9RUuj4ryxBvcVTDuroCTaHsgGpExSeSqqOC4sQJgXyafj6VrwtvXkiNCdahRq77OvLO6Gu1PWcpzOXrzS/2cO6N+3oy53ermI5Ag+Cimhl41iOgcxelgMiAU/P4/YLYe5ew5ZmZSKJNnVswvULink4EM7HgCb362iq9g5xAZmW6zhANodAPPOphhcnunrgZXZJYUmE8v1iXuVXRvCM00qzWAc3FkMgxksdJWhUmFoBGCtu+wL3TYX7i72BVI32pPNrd1E5S1C3zkiVyWrX8nTnBFD1nbSHq5iFlarVMX2U1pBS+AwdP452Fz3yLnDELenG3ZCgk2wuGrMhfwn7B8co2oLRaWx7X4aXp/v7uVjUrBs/A73ZQRih2qMawt1b/sf2kPPSF2/+iHAVzd+DVNakbEyGZsg4pA/mxYK527B2gHgcj70WAt5iIdAxLMm71Pn4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
